### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 15000
}


### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "ce767abbfbd0453d8732e63c4ac2431c",
  "accountNumber": "1000000000",
  "amount": 25000
}

### query transaction
GET http://localhost:8080/transaction/4936114f34db478db6c8a17fbc490fa4
