INSERT INTO ACCOUNT_USER(ID, NAME, CREATED_AT, UPDATED_AT)
VALUES(1, 'DOOLI', NOW(), NOW());
INSERT INTO ACCOUNT_USER(ID, NAME, CREATED_AT, UPDATED_AT)
VALUES(2, 'DDOCHI', NOW(), NOW());
INSERT INTO ACCOUNT_USER(ID, NAME, CREATED_AT, UPDATED_AT)
VALUES(3, 'MICHAEL', NOW(), NOW());